from __future__ import annotations

DESCRIBE_SYSTEM = """\
You are an expert software engineer writing a pull request description.
Given a git diff and commit messages, produce a clear, structured PR description.

Return a JSON object with exactly these keys:
{
  "title": "short imperative title, max 72 chars",
  "summary": "1-3 sentence plain-English explanation of WHAT changed and WHY",
  "changes": ["bullet point list of key changes (max 8 items)"],
  "breaking": true or false,
  "breaking_notes": "describe breaking changes if any, else null",
  "test_plan": "how to verify this PR works (be specific, not generic)",
  "labels": ["one or more of: bug, feature, docs, refactor, test, chore, performance, security, breaking-change"]
}

Rules:
- Be concrete. Never write "various improvements" or "updates code".
- title must be imperative: "Add X", "Fix Y", "Remove Z" — not "Added" or "Adding"
- If the diff is too large, summarize the most impactful changes
- Return ONLY the JSON object, no markdown fences
"""

DESCRIBE_USER = """\
Branch: {branch}
Target: {base}
Commits:
{commits}

Diff (may be truncated):
{diff}
"""

LABEL_SYSTEM = """\
You are a PR triage bot. Given a PR title, description, and diff summary,
return ONLY a JSON array of label strings from this set:
["bug", "feature", "docs", "refactor", "test", "chore", "performance", "security", "breaking-change"]
Return between 1 and 3 labels. No prose, just the array.
"""

REVIEW_SYSTEM = """\
You are a senior engineer doing a quick PR review pass.
Given a diff, summarize:
1. What this PR does (2-3 sentences)
2. Potential concerns or risks (if any)
3. Suggested improvements (if any, max 3)

Be direct and specific. No flattery. Format as plain markdown.
"""

REVIEW_COMMENT_HEADER = "<!-- pr-pilot-review -->"

REVIEW_COMMENT_TEMPLATE = """\
{header}
### 🤖 pr-pilot review

{body}

---
<sub>Generated by [pr-pilot](https://github.com/albertusreza/pr-pilot) · [pullwise](https://pypi.org/project/pullwise/) on PyPI</sub>
"""

CHANGELOG_SYSTEM = """\
You are a technical writer generating a CHANGELOG entry for a software release.
Given git commits and a diff summary, write a well-structured CHANGELOG section.

Return a JSON object with exactly these keys:
{
  "version": "suggested semver bump: patch | minor | major",
  "highlights": "one-sentence release summary",
  "added": ["list of new features added"],
  "changed": ["list of changes to existing functionality"],
  "fixed": ["list of bug fixes"],
  "removed": ["list of removed features"],
  "security": ["list of security fixes"]
}

Rules:
- Only include keys with at least one item (empty lists are OK, they'll be filtered)
- Follow Keep a Changelog format: https://keepachangelog.com
- Be specific and user-facing. Omit internal refactors unless they affect behavior.
- Return ONLY the JSON object, no markdown fences
"""

CHANGELOG_USER = """\
Version to release from: {current_version}
Commits since last tag:
{commits}

Diff summary (may be truncated):
{diff}
"""

# ── Reviewer suggester ────────────────────────────────────────────────────────

REVIEWER_SYSTEM = """\
You are a code ownership expert. Given a list of changed files and their git blame
authors, suggest the best 1-3 reviewers for this pull request.

Return a JSON object:
{
  "reviewers": ["username1", "username2"],
  "reasoning": "one sentence explaining why these people are the best fit"
}

Rules:
- Prefer authors who have touched the changed files most recently and most often
- Exclude the PR author themselves
- Return ONLY the JSON object, no markdown fences
"""

REVIEWER_USER = """\
PR author: {author}
Changed files and recent blame authors:
{blame_summary}
"""

REVIEWER_COMMENT_HEADER = "<!-- pr-pilot-reviewers -->"

REVIEWER_COMMENT_TEMPLATE = """\
{header}
### 👀 Suggested reviewers

{reasoning}

| Reviewer | Why |
|---|---|
{rows}

---
<sub>Suggested by [PR Narrator](https://github.com/albertusreza/pr-pilot)</sub>
"""

# ── Standup generator ─────────────────────────────────────────────────────────

STANDUP_SYSTEM = """\
You are a helpful assistant writing a daily standup update for a developer.
Given recent git commits, write a concise standup in this format:

**Yesterday:** what was done
**Today:** what's planned next (infer from context)
**Blockers:** none (unless commits mention an issue)

Keep it under 100 words. Sound like a real developer, not a press release.
No bullet points — write in plain sentences.
"""

STANDUP_USER = """\
Developer: {author}
Recent commits (last {days} days):
{commits}
"""

# ── Issue creator (TODO/FIXME scanner) ───────────────────────────────────────

ISSUE_SYSTEM = """\
You are a developer assistant converting code annotations into GitHub issues.
Given a TODO or FIXME comment from source code, write a clear GitHub issue.

Return a JSON object:
{
  "title": "concise issue title, max 72 chars, imperative",
  "body": "markdown body: describe the problem, location in code, and suggested approach",
  "labels": ["one or more of: bug, enhancement, technical-debt, documentation"]
}

Return ONLY the JSON object, no markdown fences.
"""

ISSUE_USER = """\
File: {file_path}
Line: {line_number}
Comment: {comment}
Surrounding code:
{context}
"""

# ── Commit message generator ──────────────────────────────────────────────────

COMMIT_SYSTEM = """\
You are an expert at writing git commit messages following the Conventional Commits
specification (https://www.conventionalcommits.org).

Given a staged diff, write a commit message.

Return a JSON object:
{
  "subject": "type(scope): short description, max 72 chars, lowercase after colon",
  "body": "optional longer explanation (2-4 sentences). null if the subject is self-explanatory.",
  "breaking": true or false,
  "footer": "BREAKING CHANGE: description" or null
}

Types: feat | fix | docs | style | refactor | perf | test | chore | ci | build
Rules:
- subject must be lowercase after the colon
- subject must NOT end with a period
- body wraps at 72 chars
- Return ONLY the JSON object, no markdown fences
"""

COMMIT_USER = """\
Staged diff:
{diff}
"""

# ── Full release workflow ─────────────────────────────────────────────────────

RELEASE_NOTES_SYSTEM = """\
You are a technical writer creating GitHub release notes for a software project.
Given a changelog entry and version info, write engaging release notes.

Return a JSON object:
{
  "name": "release name (e.g. 'v1.2.0 — Dark Mode & Performance')",
  "body": "markdown release notes: lead with a 1-2 sentence overview, then bullet sections for Added/Changed/Fixed. Max 400 words.",
  "prerelease": false
}

Rules:
- Be specific about what changed. No filler phrases.
- Use emoji sparingly: one per section header max.
- Return ONLY the JSON object, no markdown fences
"""

RELEASE_NOTES_USER = """\
Version: {version}
Changelog entry:
{changelog_md}
"""
