from __future__ import annotations

DESCRIBE_SYSTEM = """\
You are an expert software engineer writing a pull request description.
Given a git diff and commit messages, produce a clear, structured PR description.

Return a JSON object with exactly these keys:
{
  "title": "short imperative title, max 72 chars",
  "summary": "1-3 sentence plain-English explanation of WHAT changed and WHY",
  "changes": ["bullet point list of key changes (max 8 items)"],
  "breaking": true or false,
  "breaking_notes": "describe breaking changes if any, else null",
  "test_plan": "how to verify this PR works (be specific, not generic)",
  "labels": ["one or more of: bug, feature, docs, refactor, test, chore, performance, security, breaking-change"]
}

Rules:
- Be concrete. Never write "various improvements" or "updates code".
- title must be imperative: "Add X", "Fix Y", "Remove Z" — not "Added" or "Adding"
- If the diff is too large, summarize the most impactful changes
- Return ONLY the JSON object, no markdown fences
"""

DESCRIBE_USER = """\
Branch: {branch}
Target: {base}
Commits:
{commits}

Diff (may be truncated):
{diff}
"""

LABEL_SYSTEM = """\
You are a PR triage bot. Given a PR title, description, and diff summary,
return ONLY a JSON array of label strings from this set:
["bug", "feature", "docs", "refactor", "test", "chore", "performance", "security", "breaking-change"]
Return between 1 and 3 labels. No prose, just the array.
"""

REVIEW_SYSTEM = """\
You are a senior engineer doing a quick PR review pass.
Given a diff, summarize:
1. What this PR does (2-3 sentences)
2. Potential concerns or risks (if any)
3. Suggested improvements (if any, max 3)

Be direct and specific. No flattery. Format as plain markdown.
"""

REVIEW_COMMENT_HEADER = "<!-- pr-pilot-review -->"

REVIEW_COMMENT_TEMPLATE = """\
{header}
### 🤖 pr-pilot review

{body}

---
<sub>Generated by [pr-pilot](https://github.com/albertusreza/pr-pilot) · [pullwise](https://pypi.org/project/pullwise/) on PyPI</sub>
"""

CHANGELOG_SYSTEM = """\
You are a technical writer generating a CHANGELOG entry for a software release.
Given git commits and a diff summary, write a well-structured CHANGELOG section.

Return a JSON object with exactly these keys:
{
  "version": "suggested semver bump: patch | minor | major",
  "highlights": "one-sentence release summary",
  "added": ["list of new features added"],
  "changed": ["list of changes to existing functionality"],
  "fixed": ["list of bug fixes"],
  "removed": ["list of removed features"],
  "security": ["list of security fixes"]
}

Rules:
- Only include keys with at least one item (empty lists are OK, they'll be filtered)
- Follow Keep a Changelog format: https://keepachangelog.com
- Be specific and user-facing. Omit internal refactors unless they affect behavior.
- Return ONLY the JSON object, no markdown fences
"""

CHANGELOG_USER = """\
Version to release from: {current_version}
Commits since last tag:
{commits}

Diff summary (may be truncated):
{diff}
"""
